baseURL = "http://clipper.ai/"
languageCode = "en-us"
title = "Clipper"
theme = "hugo-theme-learn"
# PygmentsCodeFences = true
PygmentsStyle = "monokai"
# Simon <xmo@berkeley.edu> has the ga account
googleAnalytics = "UA-143524082-2"

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-book'></i> API Docs"
identifier = "apidoc"
url = "http://docs.clipper.ai/en/v0.4.1/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-book'></i> REST API"
identifier = "restapidoc"
# url = "http://clipper.ai/api/api.html"
url = "http://clipper.ai/api/api.html"
weight = 15

# [[menu.shortcuts]]
# name = "RISE Lab"
# identifier = "risesite"
# url = "https://rise.cs.berkeley.edu"
# weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ghrepo"
url = "https://github.com/ucbrise/clipper"
weight = 20

#
# [[menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30
